'use client'
import {useEffect,useMemo,useState} from 'react'
import {createSupabaseBrowser} from '../lib/supabase-browser'

type Ticket={id:string;room_id:string;profile_id:string;category:string;description:string|null;status:string;appointment_at:string|null;appointment_status:string;appointment_note:string|null;closed_at:string|null;created_at:string}
type Room={id:string;room_no:string};type Profile={id:string;full_name:string|null}
const statusLabel:Record<string,string>={submitted:'งานใหม่',accepted:'รับงานแล้ว',scheduled:'นัดหมาย',in_progress:'กำลังซ่อม',completed:'เสร็จแล้วแต่ยังไม่ปิด',cancelled:'ยกเลิก'}
export default function AdminRepairManager(){
 const supabase=useMemo(()=>createSupabaseBrowser(),[])
 const [tickets,setTickets]=useState<Ticket[]>([]),[rooms,setRooms]=useState<Record<string,string>>({}),[people,setPeople]=useState<Record<string,string>>({})
 const [appointment,setAppointment]=useState<Record<string,string>>({}),[note,setNote]=useState<Record<string,string>>({}),[status,setStatus]=useState('กำลังโหลด...')
 const load=async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setStatus('กรุณาเข้าสู่ระบบ');return};const {data:p}=await supabase.from('profiles').select('tenant_id,role').eq('auth_user_id',user.id).maybeSingle();if(!p||!['owner','admin','staff'].includes(p.role)){setStatus('ไม่มีสิทธิ์');return}
  const {data:t,error}=await supabase.from('maintenance_tickets').select('id,room_id,profile_id,category,description,status,appointment_at,appointment_status,appointment_note,closed_at,created_at').order('created_at',{ascending:false}).limit(100);if(error){setStatus(error.message);return};const rows=(t||[]) as Ticket[];setTickets(rows)
  const roomIds=[...new Set(rows.map(x=>x.room_id))], profileIds=[...new Set(rows.map(x=>x.profile_id))];if(roomIds.length){const {data:r}=await supabase.from('rooms').select('id,room_no').in('id',roomIds);setRooms(Object.fromEntries(((r||[]) as Room[]).map(x=>[x.id,x.room_no])))};if(profileIds.length){const {data:q}=await supabase.from('profiles').select('id,full_name').in('id',profileIds);setPeople(Object.fromEntries(((q||[]) as Profile[]).map(x=>[x.id,x.full_name||'ผู้เช่า'])))};setStatus('พร้อมจัดการ')}
 useEffect(()=>{load()},[])
 const move=async(id:string,to:string)=>{setStatus('กำลังเปลี่ยนสถานะ...');const {error}=await supabase.rpc('transition_maintenance_ticket',{p_ticket_id:id,p_to_status:to,p_note:note[id]||null});setStatus(error?error.message:'อัปเดตสถานะแล้ว');await load()}
 const setAppt=async(id:string)=>{if(!appointment[id])return;setStatus('กำลังตั้งนัด...');const {error}=await supabase.rpc('set_maintenance_appointment',{p_ticket_id:id,p_appointment_at:new Date(appointment[id]).toISOString(),p_note:note[id]||null});setStatus(error?error.message:'ตั้งนัดแล้ว · รอผู้เช่ายืนยัน');await load()}
 const close=async(id:string)=>{setStatus('กำลังปิดงาน...');const {error}=await supabase.rpc('close_maintenance_ticket',{p_ticket_id:id,p_note:note[id]||null});setStatus(error?error.message:'ปิดงานแล้ว');await load()}
 const open=tickets.filter(x=>!x.closed_at),closed=tickets.filter(x=>x.closed_at)
 const count=(s:string)=>open.filter(x=>x.status===s).length
 return <>
  <div className="metricGrid"><div className="metric"><span className="muted">งานใหม่</span><strong>{count('submitted')}</strong></div><div className="metric"><span className="muted">รับงานแล้ว</span><strong>{count('accepted')+count('scheduled')}</strong></div><div className="metric"><span className="muted">กำลังซ่อม</span><strong>{count('in_progress')}</strong></div><div className="metric"><span className="muted">เสร็จแต่ยังไม่ปิด</span><strong>{count('completed')}</strong></div></div>
  <section className="section card"><div className="toolbar"><div><h2>คิวงานซ่อม</h2><p className="muted">งานจะค้างอยู่จนเจ้าของกด “ปิดงาน” เท่านั้น</p></div><span className="pill">{status}</span></div>{open.length===0?<p className="muted">ไม่มีงานค้าง</p>:open.map(t=><div className="card section" key={t.id}><div className="toolbar"><div><strong>ห้อง {rooms[t.room_id]||'—'} · {people[t.profile_id]||'ผู้เช่า'}</strong><div>{t.category} · {t.description||'—'}</div></div><span className="pill">{statusLabel[t.status]||t.status}</span></div>{t.appointment_at&&<div className="infoRow"><span className="muted">นัด</span><strong>{new Date(t.appointment_at).toLocaleString('th-TH')} · {t.appointment_status}</strong></div>}<div className="formGrid section"><label>วันเวลานัด<input type="datetime-local" value={appointment[t.id]||''} onChange={e=>setAppointment({...appointment,[t.id]:e.target.value})}/></label><label>หมายเหตุ<input value={note[t.id]||''} onChange={e=>setNote({...note,[t.id]:e.target.value})}/></label></div><div className="flow section">{t.status==='submitted'&&<button className="btn" onClick={()=>move(t.id,'accepted')}>รับงาน</button>}<button className="btn secondary" onClick={()=>setAppt(t.id)}>ตั้ง/แก้นัด</button>{['accepted','scheduled'].includes(t.status)&&<button className="btn secondary" onClick={()=>move(t.id,'in_progress')}>เริ่มซ่อม</button>}{t.status==='in_progress'&&<button className="btn secondary" onClick={()=>move(t.id,'completed')}>ทำเสร็จ</button>}{['completed','cancelled'].includes(t.status)&&<button className="btn" onClick={()=>close(t.id)}>ปิดงาน</button>}</div></div>)}</section>
  <section className="section card"><h3>ประวัติงานที่ปิดแล้ว</h3><p className="muted">{closed.length} งาน · เก็บย้อนหลัง ไม่ลบข้อมูล</p></section>
 </>
}
