'use client'
import {FormEvent,useEffect,useMemo,useState} from 'react'
import {PDFDocument} from 'pdf-lib'
import {createSupabaseBrowser} from '../lib/supabase-browser'
import SignatureCanvas from './SignatureCanvas'

type Room={id:string;room_no:string;monthly_rent:number;deposit_amount:number}
type Profile={id:string;full_name:string|null;phone:string|null}
type Lease={id:string;room_id:string;profile_id:string;start_date:string;end_date:string|null;rent_amount:number;deposit_amount:number;status:string;contract_version:number;tenant_signed_at:string|null;admin_signed_at:string|null;final_pdf_path:string|null;contract_snapshot:any}
type Sig={signer_role:string;signature_path:string}
const loadImg=(src:string)=>new Promise<HTMLImageElement>((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=src})
function wrap(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,max:number,line=46){const words=text.split(/\s+/);let row='',yy=y;for(const w of words){const test=row?row+' '+w:w;if(ctx.measureText(test).width>max&&row){ctx.fillText(row,x,yy);row=w;yy+=line}else row=test}if(row)ctx.fillText(row,x,yy);return yy}
export default function ContractManager(){
 const supabase=useMemo(()=>createSupabaseBrowser(),[])
 const [tenantId,setTenantId]=useState(''),[rooms,setRooms]=useState<Room[]>([]),[people,setPeople]=useState<Profile[]>([]),[leases,setLeases]=useState<Lease[]>([])
 const [roomId,setRoomId]=useState(''),[profileId,setProfileId]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[rent,setRent]=useState(0),[deposit,setDeposit]=useState(0),[terms,setTerms]=useState(''),[status,setStatus]=useState('กำลังโหลด...')
 const load=async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setStatus('กรุณาเข้าสู่ระบบ');return};const {data:p}=await supabase.from('profiles').select('tenant_id,role').eq('auth_user_id',user.id).maybeSingle();if(!p||!['owner','admin','staff'].includes(p.role)){setStatus('ไม่มีสิทธิ์');return};setTenantId(p.tenant_id)
 const [{data:r},{data:u},{data:l}]=await Promise.all([supabase.from('rooms').select('id,room_no,monthly_rent,deposit_amount').eq('is_enabled',true).order('room_no'),supabase.from('profiles').select('id,full_name,phone').eq('tenant_id',p.tenant_id).eq('role','tenant').order('full_name'),supabase.from('leases').select('id,room_id,profile_id,start_date,end_date,rent_amount,deposit_amount,status,contract_version,tenant_signed_at,admin_signed_at,final_pdf_path,contract_snapshot').order('created_at',{ascending:false}).limit(100)]);setRooms((r||[]) as Room[]);setPeople((u||[]) as Profile[]);setLeases((l||[]) as Lease[]);setStatus('พร้อมจัดการสัญญา')}
 useEffect(()=>{load()},[])
 const chooseRoom=(id:string)=>{setRoomId(id);const r=rooms.find(x=>x.id===id);if(r){setRent(Number(r.monthly_rent));setDeposit(Number(r.deposit_amount))}}
 const createDraft=async(e:FormEvent)=>{e.preventDefault();if(!roomId||!profileId||!start)return;setStatus('กำลังสร้างร่าง...');const person=people.find(x=>x.id===profileId),room=rooms.find(x=>x.id===roomId);const snapshot={lessor:{source:'tenant_admin'},lessee:{name:person?.full_name||'',phone:person?.phone||''},room:{id:roomId,room_no:room?.room_no||''},start_date:start,end_date:end||null,rent_amount:rent,deposit_amount:deposit,terms};const {error}=await supabase.rpc('create_contract_draft',{p_room_id:roomId,p_profile_id:profileId,p_start_date:start,p_end_date:end||null,p_rent:rent,p_deposit:deposit,p_snapshot:snapshot});setStatus(error?error.message:'สร้างร่างสัญญาแล้ว');if(!error)await load()}
 const sign=async(lease:Lease,blob:Blob)=>{if(!tenantId)return;setStatus('กำลังบันทึกลายเซ็นเจ้าของ...');const path=`${tenantId}/${lease.id}/owner-${Date.now()}.png`;const {error:up}=await supabase.storage.from('stayhub-contracts').upload(path,blob,{contentType:'image/png',upsert:false});if(up){setStatus(up.message);return};const {error}=await supabase.rpc('record_contract_signature',{p_lease_id:lease.id,p_signer_role:'owner',p_signature_path:path,p_user_agent:navigator.userAgent});setStatus(error?error.message:'บันทึกลายเซ็นเจ้าของแล้ว');if(!error)await load()}
 const finalize=async(lease:Lease)=>{if(!tenantId)return;setStatus('กำลังสร้าง PDF Final...');const {data:sigs,error:sigErr}=await supabase.from('contract_signatures').select('signer_role,signature_path').eq('lease_id',lease.id).order('signed_at',{ascending:true});if(sigErr){setStatus(sigErr.message);return};const latest:Record<string,Sig>={};for(const s of (sigs||[]) as Sig[])latest[s.signer_role]=s;if(!latest.tenant||(!latest.owner&&!latest.admin)){setStatus('ยังมีลายเซ็นไม่ครบ');return}
 const ownerSig=latest.owner||latest.admin;const [tu,ou]=await Promise.all([supabase.storage.from('stayhub-contracts').createSignedUrl(latest.tenant.signature_path,120),supabase.storage.from('stayhub-contracts').createSignedUrl(ownerSig.signature_path,120)]);if(!tu.data?.signedUrl||!ou.data?.signedUrl){setStatus('เปิดลายเซ็นเพื่อสร้าง PDF ไม่สำเร็จ');return}
 const c=document.createElement('canvas');c.width=1240;c.height=1754;const ctx=c.getContext('2d');if(!ctx)return;ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#111';ctx.font='bold 48px sans-serif';ctx.textAlign='center';ctx.fillText('สัญญาเช่าที่พักอาศัย',620,90);ctx.textAlign='left';ctx.font='30px sans-serif';const snap=lease.contract_snapshot||{},room=rooms.find(x=>x.id===lease.room_id),person=people.find(x=>x.id===lease.profile_id);let y=170;const line=(a:string,b:string)=>{ctx.fillText(`${a}: ${b}`,90,y);y+=55};line('เลขห้อง',room?.room_no||snap.room?.room_no||'—');line('ผู้เช่า',person?.full_name||snap.lessee?.name||'—');line('โทร',person?.phone||snap.lessee?.phone||'—');line('วันเริ่ม',lease.start_date);line('วันสิ้นสุด',lease.end_date||'ไม่ระบุ');line('ค่าเช่าต่อเดือน',`${Number(lease.rent_amount).toLocaleString('th-TH')} บาท`);line('เงินประกัน',`${Number(lease.deposit_amount).toLocaleString('th-TH')} บาท`);ctx.font='28px sans-serif';ctx.fillText('เงื่อนไขเพิ่มเติม',90,y);y+=45;wrap(ctx,String(snap.terms||'เป็นไปตามเงื่อนไขที่คู่สัญญาตกลงและข้อมูลในสัญญาฉบับนี้'),90,y,1060,42);ctx.font='24px sans-serif';ctx.fillText(`Contract version ${lease.contract_version} · Lease ID ${lease.id}`,90,1120);const [tenantImg,ownerImg]=await Promise.all([loadImg(tu.data.signedUrl),loadImg(ou.data.signedUrl)]);ctx.font='28px sans-serif';ctx.fillText('ลายเซ็นผู้เช่า',120,1260);ctx.fillText('ลายเซ็นเจ้าของ/แอดมิน',700,1260);ctx.drawImage(tenantImg,100,1300,380,170);ctx.drawImage(ownerImg,680,1300,380,170);ctx.font='22px sans-serif';ctx.fillText(`ผู้เช่าเซ็น: ${lease.tenant_signed_at?new Date(lease.tenant_signed_at).toLocaleString('th-TH'):'—'}`,100,1510);ctx.fillText(`เจ้าของเซ็น: ${lease.admin_signed_at?new Date(lease.admin_signed_at).toLocaleString('th-TH'):'—'}`,680,1510);ctx.fillText('เอกสารฉบับนี้สร้างจาก snapshot และลายเซ็นที่บันทึกใน StayHub',100,1640)
 const png=c.toDataURL('image/png');const pdf=await PDFDocument.create();const page=pdf.addPage([595.28,841.89]);const image=await pdf.embedPng(png);page.drawImage(image,{x:0,y:0,width:595.28,height:841.89});pdf.setTitle(`StayHub Contract ${room?.room_no||lease.id}`);const bytes=await pdf.save();const pdfBuffer=new Uint8Array(bytes).buffer;const path=`${tenantId}/${lease.id}/final-v${lease.contract_version}.pdf`;const {error:up}=await supabase.storage.from('stayhub-contracts').upload(path,new Blob([pdfBuffer],{type:'application/pdf'}),{contentType:'application/pdf',upsert:false});if(up){setStatus(up.message);return};const {error}=await supabase.rpc('finalize_contract',{p_lease_id:lease.id,p_pdf_path:path});setStatus(error?error.message:'สร้าง PDF Final และล็อกสัญญาแล้ว');if(!error)await load()}
 return <>
  <form className="card" onSubmit={createDraft}><div className="toolbar"><div><h2>สร้างสัญญา Paperless</h2><p className="muted">สร้างร่างจากห้องและผู้เช่าจริง แล้วเก็บ snapshot เพื่อ audit</p></div><span className="pill">{status}</span></div><div className="formGrid section"><label>ห้อง<select value={roomId} onChange={e=>chooseRoom(e.target.value)} required><option value="">เลือกห้อง</option>{rooms.map(r=><option key={r.id} value={r.id}>{r.room_no}</option>)}</select></label><label>ผู้เช่า<select value={profileId} onChange={e=>setProfileId(e.target.value)} required><option value="">เลือกผู้เช่า</option>{people.map(p=><option key={p.id} value={p.id}>{p.full_name||'ผู้เช่า'}</option>)}</select></label><label>วันเริ่ม<input type="date" value={start} onChange={e=>setStart(e.target.value)} required/></label><label>วันสิ้นสุด<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>ค่าเช่าต่อเดือน<input type="number" min="0" value={rent} onChange={e=>setRent(Number(e.target.value))}/></label><label>เงินประกัน<input type="number" min="0" value={deposit} onChange={e=>setDeposit(Number(e.target.value))}/></label><label className="span2">เงื่อนไขเพิ่มเติม<textarea rows={4} value={terms} onChange={e=>setTerms(e.target.value)} placeholder="เงื่อนไขเฉพาะของหอ"/></label></div><button className="btn">สร้างร่างสัญญา</button></form>
  <section className="section card"><h2>สัญญาทั้งหมด</h2>{leases.length===0?<p className="muted">ยังไม่มีสัญญา</p>:leases.map(l=>{const room=rooms.find(x=>x.id===l.room_id),person=people.find(x=>x.id===l.profile_id);return <div className="card section" key={l.id}><div className="toolbar"><div><strong>ห้อง {room?.room_no||'—'} · {person?.full_name||'ผู้เช่า'}</strong><div className="muted">{l.start_date} → {l.end_date||'ไม่ระบุ'} · {Number(l.rent_amount).toLocaleString()} บาท/เดือน</div></div><span className="pill">{l.status}</span></div><div className="infoRow"><span className="muted">ผู้เช่าเซ็น</span><strong>{l.tenant_signed_at?new Date(l.tenant_signed_at).toLocaleString('th-TH'):'ยังไม่เซ็น'}</strong></div><div className="infoRow"><span className="muted">เจ้าของเซ็น</span><strong>{l.admin_signed_at?new Date(l.admin_signed_at).toLocaleString('th-TH'):'ยังไม่เซ็น'}</strong></div>{!l.admin_signed_at&&!l.final_pdf_path&&<div className="section"><h3>ลายเซ็นเจ้าของ</h3><SignatureCanvas onSave={b=>sign(l,b)} label="บันทึกลายเซ็นเจ้าของ"/></div>}{l.tenant_signed_at&&l.admin_signed_at&&!l.final_pdf_path&&<div className="noticeBox section"><strong>เซ็นครบแล้ว</strong><p className="muted">สร้าง PDF Final จาก snapshot + ลายเซ็น แล้วล็อกฉบับนี้</p><button type="button" className="btn" onClick={()=>finalize(l)}>สร้าง PDF Final</button></div>}{l.final_pdf_path&&<div className="noticeBox section"><strong>PDF Final · ล็อกแล้ว</strong><p className="muted">สัญญาฉบับนี้แก้ข้อมูลสำคัญย้อนหลังไม่ได้</p></div>}</div>})}</section>
 </>
}
