'use client'
import {useEffect,useMemo,useState} from 'react'
import {createSupabaseBrowser} from '../lib/supabase-browser'
import SignatureCanvas from './SignatureCanvas'
import {finalizeSignedContract} from '../lib/finalize-contract-client'

type Lease={id:string;tenant_id:string;room_id:string;start_date:string;end_date:string|null;rent_amount:number;deposit_amount:number;status:string;contract_version:number;contract_snapshot:any;tenant_signed_at:string|null;admin_signed_at:string|null;final_pdf_path:string|null}
export default function ResidentContractPanel(){
 const supabase=useMemo(()=>createSupabaseBrowser(),[])
 const [lease,setLease]=useState<Lease|null>(null),[roomNo,setRoomNo]=useState('—'),[status,setStatus]=useState('กำลังโหลด...'),[pdfUrl,setPdfUrl]=useState('')
 const load=async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setStatus('กรุณาเข้าสู่ระบบ');return};const {data:p}=await supabase.from('profiles').select('id').eq('auth_user_id',user.id).maybeSingle();if(!p){setStatus('ไม่พบข้อมูลผู้เช่า');return};const {data:l,error}=await supabase.from('leases').select('id,tenant_id,room_id,start_date,end_date,rent_amount,deposit_amount,status,contract_version,contract_snapshot,tenant_signed_at,admin_signed_at,final_pdf_path').eq('profile_id',p.id).in('status',['draft','sent','tenant_signed','active']).order('created_at',{ascending:false}).limit(1).maybeSingle();if(error||!l){setStatus('ยังไม่มีสัญญาที่เปิดให้ดู');return};setLease(l as Lease);const {data:r}=await supabase.from('rooms').select('room_no').eq('id',l.room_id).maybeSingle();setRoomNo(r?.room_no||'—');if(l.final_pdf_path){const {data:u}=await supabase.storage.from('stayhub-contracts').createSignedUrl(l.final_pdf_path,600);setPdfUrl(u?.signedUrl||'')}setStatus('พร้อมอ่านและเซ็น')}
 useEffect(()=>{load()},[])
 const sign=async(blob:Blob)=>{if(!lease)return;setStatus('กำลังบันทึกลายเซ็น...');const path=`${lease.tenant_id}/${lease.id}/tenant-${Date.now()}.png`;const {error:up}=await supabase.storage.from('stayhub-contracts').upload(path,blob,{contentType:'image/png',upsert:false});if(up){setStatus(up.message);return};const {error}=await supabase.rpc('record_contract_signature',{p_lease_id:lease.id,p_signer_role:'tenant',p_signature_path:path,p_user_agent:navigator.userAgent});if(error){setStatus(error.message);return};const res=await finalizeSignedContract({supabase,lease,snapshot:lease.contract_snapshot||{},roomNo});setStatus(res.ok?'เซ็นครบ 2 ฝ่ายแล้ว · สร้าง PDF Final แล้ว':res.pending?'เซ็นสัญญาแล้ว · รอเจ้าของหอเซ็น':res.error||'เซ็นสัญญาแล้ว');await load()}
 if(!lease)return <section className="card"><h2>สัญญาปัจจุบัน</h2><p className="muted">{status}</p></section>
 const snap=lease.contract_snapshot||{},terms=Array.isArray(snap.terms)?snap.terms:[snap.terms].filter(Boolean)
 return <>
  <section className="card"><div className="toolbar"><div><span className="pill">Paperless</span><h2>{snap.title||`สัญญาห้อง ${roomNo}`}</h2><p className="muted">Version {lease.contract_version} · {status}</p></div><span className="pill">{lease.status}</span></div></section>
  <section className="section card"><h3>รายละเอียดสัญญา</h3><div className="infoRow"><span>ผู้ให้เช่า</span><strong>{snap.lessor?.name||'—'}</strong></div><div className="infoRow"><span>ที่อยู่ผู้ให้เช่า</span><strong>{snap.lessor?.address||'—'}</strong></div><div className="infoRow"><span>ผู้เช่า</span><strong>{snap.lessee?.name||'—'}</strong></div><div className="infoRow"><span>ที่อยู่ห้องเช่า</span><strong>{snap.lessee?.address||'—'}</strong></div><div className="infoRow"><span>วันเริ่ม</span><strong>{lease.start_date}</strong></div><div className="infoRow"><span>วันสิ้นสุด</span><strong>{lease.end_date||'ไม่ระบุ'}</strong></div><div className="infoRow"><span>ค่าเช่า</span><strong>{Number(lease.rent_amount).toLocaleString()} บาท</strong></div><div className="infoRow"><span>เงินประกัน</span><strong>{Number(lease.deposit_amount).toLocaleString()} บาท</strong></div>{terms.length>0&&<div className="section"><h3>ข้อตกลง</h3><ol>{terms.map((x:string,i:number)=><li key={i} style={{marginBottom:8}}>{x}</li>)}</ol></div>}</section>
  <section className="section card"><h3>สถานะการลงนาม</h3><div className="infoRow"><span>ผู้เช่า</span><strong>{lease.tenant_signed_at?'เซ็นแล้ว '+new Date(lease.tenant_signed_at).toLocaleString('th-TH'):'ยังไม่เซ็น'}</strong></div><div className="infoRow"><span>เจ้าของหอ</span><strong>{lease.admin_signed_at?'เซ็นแล้ว':'ยังไม่เซ็น'}</strong></div></section>
  {!lease.tenant_signed_at&&<section className="section card"><h3>ลงลายเซ็นผู้เช่า</h3><p className="muted">ข้อมูลสัญญาถูกดึงจากห้องแล้ว ไม่ต้องกรอกใหม่</p><SignatureCanvas onSave={sign} label="เซ็นและยืนยันสัญญา"/></section>}
  {lease.final_pdf_path&&<section className="section card"><div className="toolbar"><div><strong>PDF Final · ฝังลายเซ็นครบแล้ว</strong><p className="muted">ไฟล์สัญญาถูกล็อกหลังคู่สัญญาเซ็นครบ</p></div>{pdfUrl&&<a className="btn" href={pdfUrl} target="_blank" rel="noreferrer">เปิด PDF สัญญา</a>}</div></section>}
 </>
}
