export const stayhubRoutes = {
  public: {
    home: '/',
    tenantEntry: (tenantSlug: string) => `/t/${tenantSlug}`,
    blocked: (tenantSlug: string) => `/t/${tenantSlug}/blocked`,
  },
  resident: {
    home: (tenantSlug: string) => `/t/${tenantSlug}/app`,
    room: (tenantSlug: string) => `/t/${tenantSlug}/app/room`,
    contract: (tenantSlug: string) => `/t/${tenantSlug}/app/room/contract`,
    billing: (tenantSlug: string) => `/t/${tenantSlug}/app/billing`,
    repairs: (tenantSlug: string) => `/t/${tenantSlug}/app/repair`,
    services: (tenantSlug: string) => `/t/${tenantSlug}/app/services`,
    news: (tenantSlug: string) => `/t/${tenantSlug}/app/news`,
  },
  admin: {
    home: (tenantSlug: string) => `/t/${tenantSlug}/admin`,
    rooms: (tenantSlug: string) => `/t/${tenantSlug}/admin/rooms`,
    residents: (tenantSlug: string) => `/t/${tenantSlug}/admin/residents`,
    contracts: (tenantSlug: string) => `/t/${tenantSlug}/admin/contracts`,
    billing: (tenantSlug: string) => `/t/${tenantSlug}/admin/billing`,
    meterWalk: (tenantSlug: string) => `/t/${tenantSlug}/admin/billing/meter-walk`,
    payments: (tenantSlug: string) => `/t/${tenantSlug}/admin/billing/payments`,
    repairs: (tenantSlug: string) => `/t/${tenantSlug}/admin/repairs`,
    parcels: (tenantSlug: string) => `/t/${tenantSlug}/admin/parcels`,
    rides: (tenantSlug: string) => `/t/${tenantSlug}/admin/rides`,
    announcements: (tenantSlug: string) => `/t/${tenantSlug}/admin/announcements`,
    reports: (tenantSlug: string) => `/t/${tenantSlug}/admin/reports`,
    settings: (tenantSlug: string) => `/t/${tenantSlug}/admin/settings`,
  },
  platform: {
    home: '/platform',
    tenants: '/platform/tenants',
    tenant: (tenantId: string) => `/platform/tenants/${tenantId}`,
    subscription: (tenantId: string) => `/platform/tenants/${tenantId}/subscription`,
    access: (tenantId: string) => `/platform/tenants/${tenantId}/access`,
    billing: '/platform/billing',
    reports: '/platform/reports',
    settings: '/platform/settings',
  },
} as const
